-- Create the messages table for Supabase
-- This table handles communications between Clients, Admin, Service Centers, and CPAs.

CREATE TABLE IF NOT EXISTS public.messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id INT REFERENCES public."Clients"(client_id) ON DELETE CASCADE,
    sender_role TEXT NOT NULL, -- ADMIN, CLIENT, CPA, SERVICE_CENTER
    receiver_role TEXT NOT NULL, -- ADMIN, CLIENT, CPA, SERVICE_CENTER
    message_text TEXT NOT NULL,
    attachment_url TEXT,
    attachment_name TEXT,
    service_center_id INT REFERENCES public.service_centers(service_center_id) ON DELETE SET NULL,
    cpa_id INT REFERENCES public.cpa_centers(cpa_id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    parent_message_id BIGINT REFERENCES public.messages(id) ON DELETE SET NULL
);

-- Enable RLS (Security)
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;

-- Simple policy: Authenticated users can read/write messages
DROP POLICY IF EXISTS "Allow authenticated access to messages" ON public.messages;
CREATE POLICY "Allow authenticated access to messages" 
ON public.messages 
FOR ALL 
TO authenticated 
USING (true)
WITH CHECK (true);
