-- Create the audit_logs table for Supabase
-- This table tracks all significant actions performed in the system.

CREATE TABLE IF NOT EXISTS public.audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id INT REFERENCES public."Clients"(client_id) ON DELETE CASCADE,
    action TEXT NOT NULL,
    actor_role TEXT,
    details TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS (Security)
ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;

-- Simple policy: Authenticated users can read/write logs (Adjust as needed for your project)
DROP POLICY IF EXISTS "Allow authenticated access to audit_logs" ON public.audit_logs;

CREATE POLICY "Allow authenticated access to audit_logs" 
ON public.audit_logs 
FOR ALL 
TO authenticated 
USING (true)
WITH CHECK (true);
